services:
  url-shortener-app:
    build: .
    depends_on:
      - shortener-postgres
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://shortener-postgres:5432/postgres
      - SPRING_DATASOURCE_USERNAME=myuser
      - SPRING_DATASOURCE_PASSWORD=mypassword

    container_name: url-shortener-app

  shortener-postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    container_name: shortener-postgres
